name = "FrequencyDomainDecomposition"
uuid = "3beb752e-3a36-44e7-afd6-217947f4c8b5"
authors = ["hzgzh"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
